// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kenda/mesync/blob.proto

package mesync

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	types "gitlab.kenda.com.tw/kenda/mesync/pkg/protobuf/kenda/types"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UploadBlobRequest struct {
	Detail               []*PerUploadBlobRequest `protobuf:"bytes,1,rep,name=detail,proto3" json:"detail,omitempty"`
	StationId            string                  `protobuf:"bytes,2,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	Batch                int32                   `protobuf:"varint,3,opt,name=batch,proto3" json:"batch,omitempty"`
	ParametersHeader     []string                `protobuf:"bytes,4,rep,name=parameters_header,json=parametersHeader,proto3" json:"parameters_header,omitempty"`
	Resources            []string                `protobuf:"bytes,5,rep,name=resources,proto3" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *UploadBlobRequest) Reset()         { *m = UploadBlobRequest{} }
func (m *UploadBlobRequest) String() string { return proto.CompactTextString(m) }
func (*UploadBlobRequest) ProtoMessage()    {}
func (*UploadBlobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_338850d46219c926, []int{0}
}

func (m *UploadBlobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadBlobRequest.Unmarshal(m, b)
}
func (m *UploadBlobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadBlobRequest.Marshal(b, m, deterministic)
}
func (m *UploadBlobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadBlobRequest.Merge(m, src)
}
func (m *UploadBlobRequest) XXX_Size() int {
	return xxx_messageInfo_UploadBlobRequest.Size(m)
}
func (m *UploadBlobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadBlobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadBlobRequest proto.InternalMessageInfo

func (m *UploadBlobRequest) GetDetail() []*PerUploadBlobRequest {
	if m != nil {
		return m.Detail
	}
	return nil
}

func (m *UploadBlobRequest) GetStationId() string {
	if m != nil {
		return m.StationId
	}
	return ""
}

func (m *UploadBlobRequest) GetBatch() int32 {
	if m != nil {
		return m.Batch
	}
	return 0
}

func (m *UploadBlobRequest) GetParametersHeader() []string {
	if m != nil {
		return m.ParametersHeader
	}
	return nil
}

func (m *UploadBlobRequest) GetResources() []string {
	if m != nil {
		return m.Resources
	}
	return nil
}

type PerUploadBlobRequest struct {
	DateTime              *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	ManufactureParameters *ManufactureParameters `protobuf:"bytes,2,opt,name=manufacture_parameters,json=manufactureParameters,proto3" json:"manufacture_parameters,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *PerUploadBlobRequest) Reset()         { *m = PerUploadBlobRequest{} }
func (m *PerUploadBlobRequest) String() string { return proto.CompactTextString(m) }
func (*PerUploadBlobRequest) ProtoMessage()    {}
func (*PerUploadBlobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_338850d46219c926, []int{1}
}

func (m *PerUploadBlobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PerUploadBlobRequest.Unmarshal(m, b)
}
func (m *PerUploadBlobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PerUploadBlobRequest.Marshal(b, m, deterministic)
}
func (m *PerUploadBlobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PerUploadBlobRequest.Merge(m, src)
}
func (m *PerUploadBlobRequest) XXX_Size() int {
	return xxx_messageInfo_PerUploadBlobRequest.Size(m)
}
func (m *PerUploadBlobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PerUploadBlobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PerUploadBlobRequest proto.InternalMessageInfo

func (m *PerUploadBlobRequest) GetDateTime() *timestamp.Timestamp {
	if m != nil {
		return m.DateTime
	}
	return nil
}

func (m *PerUploadBlobRequest) GetManufactureParameters() *ManufactureParameters {
	if m != nil {
		return m.ManufactureParameters
	}
	return nil
}

type ManufactureParametersValue struct {
	// Types that are valid to be assigned to OneofName:
	//
	//	*ManufactureParametersValue_StringValue
	//	*ManufactureParametersValue_DecimalValue
	OneofName            isManufactureParametersValue_OneofName `protobuf_oneof:"oneof_name"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *ManufactureParametersValue) Reset()         { *m = ManufactureParametersValue{} }
func (m *ManufactureParametersValue) String() string { return proto.CompactTextString(m) }
func (*ManufactureParametersValue) ProtoMessage()    {}
func (*ManufactureParametersValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_338850d46219c926, []int{2}
}

func (m *ManufactureParametersValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManufactureParametersValue.Unmarshal(m, b)
}
func (m *ManufactureParametersValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManufactureParametersValue.Marshal(b, m, deterministic)
}
func (m *ManufactureParametersValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManufactureParametersValue.Merge(m, src)
}
func (m *ManufactureParametersValue) XXX_Size() int {
	return xxx_messageInfo_ManufactureParametersValue.Size(m)
}
func (m *ManufactureParametersValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ManufactureParametersValue.DiscardUnknown(m)
}

var xxx_messageInfo_ManufactureParametersValue proto.InternalMessageInfo

type isManufactureParametersValue_OneofName interface {
	isManufactureParametersValue_OneofName()
}

type ManufactureParametersValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type ManufactureParametersValue_DecimalValue struct {
	DecimalValue *types.ExpDecimal `protobuf:"bytes,2,opt,name=decimal_value,json=decimalValue,proto3,oneof"`
}

func (*ManufactureParametersValue_StringValue) isManufactureParametersValue_OneofName() {}

func (*ManufactureParametersValue_DecimalValue) isManufactureParametersValue_OneofName() {}

func (m *ManufactureParametersValue) GetOneofName() isManufactureParametersValue_OneofName {
	if m != nil {
		return m.OneofName
	}
	return nil
}

func (m *ManufactureParametersValue) GetStringValue() string {
	if x, ok := m.GetOneofName().(*ManufactureParametersValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *ManufactureParametersValue) GetDecimalValue() *types.ExpDecimal {
	if x, ok := m.GetOneofName().(*ManufactureParametersValue_DecimalValue); ok {
		return x.DecimalValue
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ManufactureParametersValue) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ManufactureParametersValue_StringValue)(nil),
		(*ManufactureParametersValue_DecimalValue)(nil),
	}
}

// This structure is used for uploading to the cloud
type BlobStoreFile struct {
	Parameters           *StationParameters `protobuf:"bytes,1,opt,name=parameters,proto3" json:"parameters,omitempty"`
	StationId            string             `protobuf:"bytes,2,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	Batch                int32              `protobuf:"varint,3,opt,name=batch,proto3" json:"batch,omitempty"`
	Resources            []string           `protobuf:"bytes,4,rep,name=resources,proto3" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BlobStoreFile) Reset()         { *m = BlobStoreFile{} }
func (m *BlobStoreFile) String() string { return proto.CompactTextString(m) }
func (*BlobStoreFile) ProtoMessage()    {}
func (*BlobStoreFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_338850d46219c926, []int{3}
}

func (m *BlobStoreFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlobStoreFile.Unmarshal(m, b)
}
func (m *BlobStoreFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlobStoreFile.Marshal(b, m, deterministic)
}
func (m *BlobStoreFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlobStoreFile.Merge(m, src)
}
func (m *BlobStoreFile) XXX_Size() int {
	return xxx_messageInfo_BlobStoreFile.Size(m)
}
func (m *BlobStoreFile) XXX_DiscardUnknown() {
	xxx_messageInfo_BlobStoreFile.DiscardUnknown(m)
}

var xxx_messageInfo_BlobStoreFile proto.InternalMessageInfo

func (m *BlobStoreFile) GetParameters() *StationParameters {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *BlobStoreFile) GetStationId() string {
	if m != nil {
		return m.StationId
	}
	return ""
}

func (m *BlobStoreFile) GetBatch() int32 {
	if m != nil {
		return m.Batch
	}
	return 0
}

func (m *BlobStoreFile) GetResources() []string {
	if m != nil {
		return m.Resources
	}
	return nil
}

type StationParameters struct {
	Details              []*BlobUnitFile `protobuf:"bytes,1,rep,name=details,proto3" json:"details,omitempty"`
	ParametersHeader     []string        `protobuf:"bytes,2,rep,name=parameters_header,json=parametersHeader,proto3" json:"parameters_header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StationParameters) Reset()         { *m = StationParameters{} }
func (m *StationParameters) String() string { return proto.CompactTextString(m) }
func (*StationParameters) ProtoMessage()    {}
func (*StationParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_338850d46219c926, []int{4}
}

func (m *StationParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StationParameters.Unmarshal(m, b)
}
func (m *StationParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StationParameters.Marshal(b, m, deterministic)
}
func (m *StationParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StationParameters.Merge(m, src)
}
func (m *StationParameters) XXX_Size() int {
	return xxx_messageInfo_StationParameters.Size(m)
}
func (m *StationParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_StationParameters.DiscardUnknown(m)
}

var xxx_messageInfo_StationParameters proto.InternalMessageInfo

func (m *StationParameters) GetDetails() []*BlobUnitFile {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *StationParameters) GetParametersHeader() []string {
	if m != nil {
		return m.ParametersHeader
	}
	return nil
}

type BlobUnitFile struct {
	DateTime              *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	ManufactureParameters *ManufactureParameters `protobuf:"bytes,2,opt,name=manufacture_parameters,json=manufactureParameters,proto3" json:"manufacture_parameters,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *BlobUnitFile) Reset()         { *m = BlobUnitFile{} }
func (m *BlobUnitFile) String() string { return proto.CompactTextString(m) }
func (*BlobUnitFile) ProtoMessage()    {}
func (*BlobUnitFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_338850d46219c926, []int{5}
}

func (m *BlobUnitFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlobUnitFile.Unmarshal(m, b)
}
func (m *BlobUnitFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlobUnitFile.Marshal(b, m, deterministic)
}
func (m *BlobUnitFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlobUnitFile.Merge(m, src)
}
func (m *BlobUnitFile) XXX_Size() int {
	return xxx_messageInfo_BlobUnitFile.Size(m)
}
func (m *BlobUnitFile) XXX_DiscardUnknown() {
	xxx_messageInfo_BlobUnitFile.DiscardUnknown(m)
}

var xxx_messageInfo_BlobUnitFile proto.InternalMessageInfo

func (m *BlobUnitFile) GetDateTime() *timestamp.Timestamp {
	if m != nil {
		return m.DateTime
	}
	return nil
}

func (m *BlobUnitFile) GetManufactureParameters() *ManufactureParameters {
	if m != nil {
		return m.ManufactureParameters
	}
	return nil
}

type ManufactureParameters struct {
	Value                []*ManufactureParametersValue `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ManufactureParameters) Reset()         { *m = ManufactureParameters{} }
func (m *ManufactureParameters) String() string { return proto.CompactTextString(m) }
func (*ManufactureParameters) ProtoMessage()    {}
func (*ManufactureParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_338850d46219c926, []int{6}
}

func (m *ManufactureParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManufactureParameters.Unmarshal(m, b)
}
func (m *ManufactureParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManufactureParameters.Marshal(b, m, deterministic)
}
func (m *ManufactureParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManufactureParameters.Merge(m, src)
}
func (m *ManufactureParameters) XXX_Size() int {
	return xxx_messageInfo_ManufactureParameters.Size(m)
}
func (m *ManufactureParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_ManufactureParameters.DiscardUnknown(m)
}

var xxx_messageInfo_ManufactureParameters proto.InternalMessageInfo

func (m *ManufactureParameters) GetValue() []*ManufactureParametersValue {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*UploadBlobRequest)(nil), "kenda.mesync.UploadBlobRequest")
	proto.RegisterType((*PerUploadBlobRequest)(nil), "kenda.mesync.PerUploadBlobRequest")
	proto.RegisterType((*ManufactureParametersValue)(nil), "kenda.mesync.ManufactureParametersValue")
	proto.RegisterType((*BlobStoreFile)(nil), "kenda.mesync.BlobStoreFile")
	proto.RegisterType((*StationParameters)(nil), "kenda.mesync.StationParameters")
	proto.RegisterType((*BlobUnitFile)(nil), "kenda.mesync.BlobUnitFile")
	proto.RegisterType((*ManufactureParameters)(nil), "kenda.mesync.ManufactureParameters")
}

func init() { proto.RegisterFile("kenda/mesync/blob.proto", fileDescriptor_338850d46219c926) }

var fileDescriptor_338850d46219c926 = []byte{
	// 520 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0xd1, 0x6a, 0xd4, 0x40,
	0x14, 0x6d, 0xba, 0xdd, 0x6a, 0xee, 0x6e, 0xc1, 0x1d, 0x5a, 0x1b, 0x16, 0xa5, 0xcb, 0xf6, 0x25,
	0x20, 0x24, 0xb0, 0x0a, 0x42, 0x91, 0x0a, 0x8b, 0xca, 0xfa, 0x20, 0x94, 0xa9, 0x55, 0xe8, 0x4b,
	0x98, 0x24, 0x77, 0xd3, 0xd0, 0x24, 0x13, 0x67, 0x26, 0xd5, 0x7e, 0x85, 0x1f, 0xe1, 0xa3, 0x1f,
	0xe3, 0x2f, 0x49, 0x32, 0x59, 0x93, 0xd8, 0x3c, 0x88, 0x4f, 0x7d, 0x09, 0xcc, 0xbd, 0xe7, 0x64,
	0xee, 0x39, 0xf7, 0x30, 0x70, 0x78, 0x8d, 0x59, 0xc8, 0xdc, 0x14, 0xe5, 0x6d, 0x16, 0xb8, 0x7e,
	0xc2, 0x7d, 0x27, 0x17, 0x5c, 0x71, 0x32, 0xae, 0x1a, 0x8e, 0x6e, 0x4c, 0x8f, 0x22, 0xce, 0xa3,
	0x04, 0xdd, 0xaa, 0xe7, 0x17, 0x6b, 0x57, 0xc5, 0x29, 0x4a, 0xc5, 0xd2, 0x5c, 0xc3, 0xa7, 0xf5,
	0x7f, 0xd4, 0x6d, 0x8e, 0x52, 0x7f, 0x75, 0x63, 0xfe, 0xcb, 0x80, 0xc9, 0x45, 0x9e, 0x70, 0x16,
	0x2e, 0x13, 0xee, 0x53, 0xfc, 0x52, 0xa0, 0x54, 0xe4, 0x04, 0x76, 0x43, 0x54, 0x2c, 0x4e, 0x2c,
	0x63, 0x36, 0xb0, 0x47, 0x8b, 0xb9, 0xd3, 0xbe, 0xce, 0x39, 0x43, 0x71, 0x87, 0x43, 0x6b, 0x06,
	0x79, 0x0a, 0x20, 0x15, 0x53, 0x31, 0xcf, 0xbc, 0x38, 0xb4, 0xb6, 0x67, 0x86, 0x6d, 0x52, 0xb3,
	0xae, 0xbc, 0x0f, 0xc9, 0x3e, 0x0c, 0x7d, 0xa6, 0x82, 0x2b, 0x6b, 0x30, 0x33, 0xec, 0x21, 0xd5,
	0x07, 0xf2, 0x0c, 0x26, 0x39, 0x13, 0x2c, 0x45, 0x85, 0x42, 0x7a, 0x57, 0xc8, 0x42, 0x14, 0xd6,
	0xce, 0x6c, 0x60, 0x9b, 0xf4, 0x51, 0xd3, 0x58, 0x55, 0x75, 0xf2, 0x04, 0x4c, 0x81, 0x92, 0x17,
	0x22, 0x40, 0x69, 0x0d, 0x2b, 0x50, 0x53, 0x98, 0xff, 0x34, 0x60, 0xbf, 0x6f, 0x40, 0xf2, 0x12,
	0xcc, 0x90, 0x29, 0xf4, 0x4a, 0x6f, 0x2c, 0x63, 0x66, 0xd8, 0xa3, 0xc5, 0xd4, 0xd1, 0xc6, 0x39,
	0x1b, 0xe3, 0x9c, 0x8f, 0x1b, 0xe3, 0xe8, 0xc3, 0x12, 0x5c, 0x1e, 0xc9, 0x25, 0x3c, 0x4e, 0x59,
	0x56, 0xac, 0x59, 0xa0, 0x0a, 0x81, 0x5e, 0x33, 0x4f, 0xa5, 0x6e, 0xb4, 0x38, 0xee, 0xba, 0xf3,
	0xa1, 0xc1, 0x9e, 0xfd, 0x81, 0xd2, 0x83, 0xb4, 0xaf, 0x3c, 0xff, 0x6e, 0xc0, 0xb4, 0x97, 0xf0,
	0x89, 0x25, 0x05, 0x92, 0x63, 0x18, 0x4b, 0x25, 0xe2, 0x2c, 0xf2, 0x6e, 0xca, 0x73, 0x35, 0xb6,
	0xb9, 0xda, 0xa2, 0x23, 0x5d, 0xd5, 0xa0, 0x53, 0xd8, 0x0b, 0x31, 0x88, 0x53, 0x96, 0xd4, 0x28,
	0x3d, 0xd6, 0x61, 0x3d, 0x96, 0x5e, 0xf7, 0xdb, 0x6f, 0xf9, 0x1b, 0x0d, 0x5a, 0x6d, 0xd1, 0x71,
	0x8d, 0xaf, 0xf8, 0xcb, 0x31, 0x00, 0xcf, 0x90, 0xaf, 0xbd, 0x8c, 0xa5, 0x38, 0xff, 0x61, 0xc0,
	0x5e, 0x69, 0xdb, 0xb9, 0xe2, 0x02, 0xdf, 0xc5, 0x09, 0x92, 0xd7, 0x00, 0x2d, 0xcd, 0xda, 0xb9,
	0xa3, 0xae, 0xe6, 0x73, 0xbd, 0xdf, 0x96, 0xde, 0x16, 0xe5, 0xff, 0x22, 0xd1, 0xd9, 0xf2, 0xce,
	0xdf, 0x5b, 0xbe, 0x81, 0xc9, 0x9d, 0x3b, 0xc9, 0x0b, 0x78, 0xa0, 0x43, 0x28, 0xeb, 0xdc, 0x4e,
	0xbb, 0x53, 0x96, 0xb2, 0x2e, 0xb2, 0x58, 0x95, 0xaa, 0xe8, 0x06, 0xda, 0x9f, 0xbd, 0xed, 0xfe,
	0xec, 0x95, 0xee, 0x8c, 0xdb, 0xbf, 0xb9, 0x9f, 0xa9, 0xfa, 0x0c, 0x07, 0xbd, 0x78, 0x72, 0x0a,
	0xc3, 0x4d, 0x90, 0x4a, 0x7f, 0xec, 0x7f, 0xb8, 0xa3, 0xca, 0x08, 0xd5, 0xb4, 0xe5, 0xab, 0xcb,
	0x93, 0x28, 0x56, 0x09, 0xf3, 0x6b, 0x62, 0xc0, 0x53, 0x47, 0x7d, 0x75, 0x3b, 0xaf, 0x54, 0x7e,
	0x1d, 0x35, 0x0f, 0x51, 0xbb, 0xe3, 0xef, 0x56, 0xe5, 0xe7, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x5d, 0x1d, 0x76, 0x5c, 0xd6, 0x04, 0x00, 0x00,
}
