// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kenda/mesync/department.proto

package mesync

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Departments struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Departments) Reset()         { *m = Departments{} }
func (m *Departments) String() string { return proto.CompactTextString(m) }
func (*Departments) ProtoMessage()    {}
func (*Departments) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac6c767d381cfe19, []int{0}
}

func (m *Departments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Departments.Unmarshal(m, b)
}
func (m *Departments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Departments.Marshal(b, m, deterministic)
}
func (m *Departments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Departments.Merge(m, src)
}
func (m *Departments) XXX_Size() int {
	return xxx_messageInfo_Departments.Size(m)
}
func (m *Departments) XXX_DiscardUnknown() {
	xxx_messageInfo_Departments.DiscardUnknown(m)
}

var xxx_messageInfo_Departments proto.InternalMessageInfo

func (m *Departments) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type UpdateDepartmentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NewId                string   `protobuf:"bytes,2,opt,name=new_id,json=newId,proto3" json:"new_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDepartmentRequest) Reset()         { *m = UpdateDepartmentRequest{} }
func (m *UpdateDepartmentRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateDepartmentRequest) ProtoMessage()    {}
func (*UpdateDepartmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac6c767d381cfe19, []int{1}
}

func (m *UpdateDepartmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDepartmentRequest.Unmarshal(m, b)
}
func (m *UpdateDepartmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDepartmentRequest.Marshal(b, m, deterministic)
}
func (m *UpdateDepartmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDepartmentRequest.Merge(m, src)
}
func (m *UpdateDepartmentRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateDepartmentRequest.Size(m)
}
func (m *UpdateDepartmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDepartmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDepartmentRequest proto.InternalMessageInfo

func (m *UpdateDepartmentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateDepartmentRequest) GetNewId() string {
	if m != nil {
		return m.NewId
	}
	return ""
}

type DeleteDepartmentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDepartmentRequest) Reset()         { *m = DeleteDepartmentRequest{} }
func (m *DeleteDepartmentRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDepartmentRequest) ProtoMessage()    {}
func (*DeleteDepartmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac6c767d381cfe19, []int{2}
}

func (m *DeleteDepartmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDepartmentRequest.Unmarshal(m, b)
}
func (m *DeleteDepartmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDepartmentRequest.Marshal(b, m, deterministic)
}
func (m *DeleteDepartmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDepartmentRequest.Merge(m, src)
}
func (m *DeleteDepartmentRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDepartmentRequest.Size(m)
}
func (m *DeleteDepartmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDepartmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDepartmentRequest proto.InternalMessageInfo

func (m *DeleteDepartmentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Departments)(nil), "kenda.mesync.Departments")
	proto.RegisterType((*UpdateDepartmentRequest)(nil), "kenda.mesync.UpdateDepartmentRequest")
	proto.RegisterType((*DeleteDepartmentRequest)(nil), "kenda.mesync.DeleteDepartmentRequest")
}

func init() { proto.RegisterFile("kenda/mesync/department.proto", fileDescriptor_ac6c767d381cfe19) }

var fileDescriptor_ac6c767d381cfe19 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcd, 0x4e, 0xcd, 0x4b,
	0x49, 0xd4, 0xcf, 0x4d, 0x2d, 0xae, 0xcc, 0x4b, 0xd6, 0x4f, 0x49, 0x2d, 0x48, 0x2c, 0x2a, 0xc9,
	0x4d, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x01, 0x4b, 0xeb, 0x41, 0xa4,
	0x95, 0xe4, 0xb9, 0xb8, 0x5d, 0xe0, 0x2a, 0x8a, 0x85, 0x04, 0xb8, 0x98, 0x33, 0x53, 0x8a, 0x25,
	0x18, 0x15, 0x98, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x25, 0x07, 0x2e, 0xf1, 0xd0, 0x82, 0x94, 0xc4,
	0x92, 0x54, 0x84, 0xb2, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x3e, 0x2e, 0xa6, 0xcc,
	0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0xa6, 0xcc, 0x14, 0x21, 0x51, 0x2e, 0xb6, 0xbc,
	0xd4, 0xf2, 0xf8, 0xcc, 0x14, 0x09, 0x26, 0xb0, 0x18, 0x6b, 0x5e, 0x6a, 0xb9, 0x67, 0x8a, 0x92,
	0x26, 0x97, 0xb8, 0x4b, 0x6a, 0x4e, 0x2a, 0x11, 0x26, 0x38, 0xd9, 0x44, 0x59, 0xa5, 0x67, 0x96,
	0xe4, 0x24, 0x26, 0xe9, 0x41, 0x1c, 0x99, 0x9c, 0x9f, 0xab, 0x57, 0x52, 0xae, 0x8f, 0xe2, 0xa1,
	0x82, 0xec, 0x74, 0x7d, 0xb0, 0x4f, 0x92, 0x4a, 0xd3, 0x50, 0x64, 0x92, 0xd8, 0xc0, 0xc2, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x5d, 0x74, 0x0d, 0x01, 0x01, 0x00, 0x00,
}
