// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kenda/mesync/recipe.proto

package mesync

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	types "gitlab.kenda.com.tw/kenda/mesync/pkg/protobuf/kenda/types"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RecipePropertyParameter struct {
	High                 *types.Decimal `protobuf:"bytes,1,opt,name=high,proto3" json:"high,omitempty"`
	Mid                  *types.Decimal `protobuf:"bytes,2,opt,name=mid,proto3" json:"mid,omitempty"`
	Low                  *types.Decimal `protobuf:"bytes,3,opt,name=low,proto3" json:"low,omitempty"`
	Unit                 string         `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RecipePropertyParameter) Reset()         { *m = RecipePropertyParameter{} }
func (m *RecipePropertyParameter) String() string { return proto.CompactTextString(m) }
func (*RecipePropertyParameter) ProtoMessage()    {}
func (*RecipePropertyParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad217bbbd342a47f, []int{0}
}

func (m *RecipePropertyParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecipePropertyParameter.Unmarshal(m, b)
}
func (m *RecipePropertyParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecipePropertyParameter.Marshal(b, m, deterministic)
}
func (m *RecipePropertyParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecipePropertyParameter.Merge(m, src)
}
func (m *RecipePropertyParameter) XXX_Size() int {
	return xxx_messageInfo_RecipePropertyParameter.Size(m)
}
func (m *RecipePropertyParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_RecipePropertyParameter.DiscardUnknown(m)
}

var xxx_messageInfo_RecipePropertyParameter proto.InternalMessageInfo

func (m *RecipePropertyParameter) GetHigh() *types.Decimal {
	if m != nil {
		return m.High
	}
	return nil
}

func (m *RecipePropertyParameter) GetMid() *types.Decimal {
	if m != nil {
		return m.Mid
	}
	return nil
}

func (m *RecipePropertyParameter) GetLow() *types.Decimal {
	if m != nil {
		return m.Low
	}
	return nil
}

func (m *RecipePropertyParameter) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

type RecipeProperty struct {
	Name                 string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Param                *RecipePropertyParameter `protobuf:"bytes,2,opt,name=param,proto3" json:"param,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *RecipeProperty) Reset()         { *m = RecipeProperty{} }
func (m *RecipeProperty) String() string { return proto.CompactTextString(m) }
func (*RecipeProperty) ProtoMessage()    {}
func (*RecipeProperty) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad217bbbd342a47f, []int{1}
}

func (m *RecipeProperty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecipeProperty.Unmarshal(m, b)
}
func (m *RecipeProperty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecipeProperty.Marshal(b, m, deterministic)
}
func (m *RecipeProperty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecipeProperty.Merge(m, src)
}
func (m *RecipeProperty) XXX_Size() int {
	return xxx_messageInfo_RecipeProperty.Size(m)
}
func (m *RecipeProperty) XXX_DiscardUnknown() {
	xxx_messageInfo_RecipeProperty.DiscardUnknown(m)
}

var xxx_messageInfo_RecipeProperty proto.InternalMessageInfo

func (m *RecipeProperty) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RecipeProperty) GetParam() *RecipePropertyParameter {
	if m != nil {
		return m.Param
	}
	return nil
}

type RecipeMaterialParameter struct {
	High                 *types.Decimal `protobuf:"bytes,1,opt,name=high,proto3" json:"high,omitempty"`
	Mid                  *types.Decimal `protobuf:"bytes,2,opt,name=mid,proto3" json:"mid,omitempty"`
	Low                  *types.Decimal `protobuf:"bytes,3,opt,name=low,proto3" json:"low,omitempty"`
	Unit                 string         `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RecipeMaterialParameter) Reset()         { *m = RecipeMaterialParameter{} }
func (m *RecipeMaterialParameter) String() string { return proto.CompactTextString(m) }
func (*RecipeMaterialParameter) ProtoMessage()    {}
func (*RecipeMaterialParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad217bbbd342a47f, []int{2}
}

func (m *RecipeMaterialParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecipeMaterialParameter.Unmarshal(m, b)
}
func (m *RecipeMaterialParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecipeMaterialParameter.Marshal(b, m, deterministic)
}
func (m *RecipeMaterialParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecipeMaterialParameter.Merge(m, src)
}
func (m *RecipeMaterialParameter) XXX_Size() int {
	return xxx_messageInfo_RecipeMaterialParameter.Size(m)
}
func (m *RecipeMaterialParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_RecipeMaterialParameter.DiscardUnknown(m)
}

var xxx_messageInfo_RecipeMaterialParameter proto.InternalMessageInfo

func (m *RecipeMaterialParameter) GetHigh() *types.Decimal {
	if m != nil {
		return m.High
	}
	return nil
}

func (m *RecipeMaterialParameter) GetMid() *types.Decimal {
	if m != nil {
		return m.Mid
	}
	return nil
}

func (m *RecipeMaterialParameter) GetLow() *types.Decimal {
	if m != nil {
		return m.Low
	}
	return nil
}

func (m *RecipeMaterialParameter) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

type RecipeMaterial struct {
	Name                 string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string                   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Grade                string                   `protobuf:"bytes,3,opt,name=grade,proto3" json:"grade,omitempty"`
	Value                *RecipeMaterialParameter `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Site                 string                   `protobuf:"bytes,5,opt,name=site,proto3" json:"site,omitempty"`
	RequiredRecipeId     string                   `protobuf:"bytes,6,opt,name=required_recipe_id,json=requiredRecipeId,proto3" json:"required_recipe_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *RecipeMaterial) Reset()         { *m = RecipeMaterial{} }
func (m *RecipeMaterial) String() string { return proto.CompactTextString(m) }
func (*RecipeMaterial) ProtoMessage()    {}
func (*RecipeMaterial) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad217bbbd342a47f, []int{3}
}

func (m *RecipeMaterial) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecipeMaterial.Unmarshal(m, b)
}
func (m *RecipeMaterial) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecipeMaterial.Marshal(b, m, deterministic)
}
func (m *RecipeMaterial) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecipeMaterial.Merge(m, src)
}
func (m *RecipeMaterial) XXX_Size() int {
	return xxx_messageInfo_RecipeMaterial.Size(m)
}
func (m *RecipeMaterial) XXX_DiscardUnknown() {
	xxx_messageInfo_RecipeMaterial.DiscardUnknown(m)
}

var xxx_messageInfo_RecipeMaterial proto.InternalMessageInfo

func (m *RecipeMaterial) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RecipeMaterial) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *RecipeMaterial) GetGrade() string {
	if m != nil {
		return m.Grade
	}
	return ""
}

func (m *RecipeMaterial) GetValue() *RecipeMaterialParameter {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *RecipeMaterial) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

func (m *RecipeMaterial) GetRequiredRecipeId() string {
	if m != nil {
		return m.RequiredRecipeId
	}
	return ""
}

type RecipeProcessStep struct {
	Materials            []*RecipeMaterial `protobuf:"bytes,1,rep,name=materials,proto3" json:"materials,omitempty"`
	Controls             []*RecipeProperty `protobuf:"bytes,2,rep,name=controls,proto3" json:"controls,omitempty"`
	Measurements         []*RecipeProperty `protobuf:"bytes,3,rep,name=measurements,proto3" json:"measurements,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RecipeProcessStep) Reset()         { *m = RecipeProcessStep{} }
func (m *RecipeProcessStep) String() string { return proto.CompactTextString(m) }
func (*RecipeProcessStep) ProtoMessage()    {}
func (*RecipeProcessStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad217bbbd342a47f, []int{4}
}

func (m *RecipeProcessStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecipeProcessStep.Unmarshal(m, b)
}
func (m *RecipeProcessStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecipeProcessStep.Marshal(b, m, deterministic)
}
func (m *RecipeProcessStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecipeProcessStep.Merge(m, src)
}
func (m *RecipeProcessStep) XXX_Size() int {
	return xxx_messageInfo_RecipeProcessStep.Size(m)
}
func (m *RecipeProcessStep) XXX_DiscardUnknown() {
	xxx_messageInfo_RecipeProcessStep.DiscardUnknown(m)
}

var xxx_messageInfo_RecipeProcessStep proto.InternalMessageInfo

func (m *RecipeProcessStep) GetMaterials() []*RecipeMaterial {
	if m != nil {
		return m.Materials
	}
	return nil
}

func (m *RecipeProcessStep) GetControls() []*RecipeProperty {
	if m != nil {
		return m.Controls
	}
	return nil
}

func (m *RecipeProcessStep) GetMeasurements() []*RecipeProperty {
	if m != nil {
		return m.Measurements
	}
	return nil
}

type RecipeTool struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Required             bool     `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecipeTool) Reset()         { *m = RecipeTool{} }
func (m *RecipeTool) String() string { return proto.CompactTextString(m) }
func (*RecipeTool) ProtoMessage()    {}
func (*RecipeTool) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad217bbbd342a47f, []int{5}
}

func (m *RecipeTool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecipeTool.Unmarshal(m, b)
}
func (m *RecipeTool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecipeTool.Marshal(b, m, deterministic)
}
func (m *RecipeTool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecipeTool.Merge(m, src)
}
func (m *RecipeTool) XXX_Size() int {
	return xxx_messageInfo_RecipeTool.Size(m)
}
func (m *RecipeTool) XXX_DiscardUnknown() {
	xxx_messageInfo_RecipeTool.DiscardUnknown(m)
}

var xxx_messageInfo_RecipeTool proto.InternalMessageInfo

func (m *RecipeTool) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *RecipeTool) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RecipeTool) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

type RecipeProcessConfig struct {
	Stations  []string       `protobuf:"bytes,1,rep,name=stations,proto3" json:"stations,omitempty"`
	BatchSize *types.Decimal `protobuf:"bytes,2,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	// It is UOM for the product.
	Unit                 string               `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Tools                []*RecipeTool        `protobuf:"bytes,4,rep,name=tools,proto3" json:"tools,omitempty"`
	Steps                []*RecipeProcessStep `protobuf:"bytes,5,rep,name=steps,proto3" json:"steps,omitempty"`
	CommonsControls      []*RecipeProperty    `protobuf:"bytes,6,rep,name=commons_controls,json=commonsControls,proto3" json:"commons_controls,omitempty"`
	CommonsProperties    []*RecipeProperty    `protobuf:"bytes,7,rep,name=commons_properties,json=commonsProperties,proto3" json:"commons_properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RecipeProcessConfig) Reset()         { *m = RecipeProcessConfig{} }
func (m *RecipeProcessConfig) String() string { return proto.CompactTextString(m) }
func (*RecipeProcessConfig) ProtoMessage()    {}
func (*RecipeProcessConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad217bbbd342a47f, []int{6}
}

func (m *RecipeProcessConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecipeProcessConfig.Unmarshal(m, b)
}
func (m *RecipeProcessConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecipeProcessConfig.Marshal(b, m, deterministic)
}
func (m *RecipeProcessConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecipeProcessConfig.Merge(m, src)
}
func (m *RecipeProcessConfig) XXX_Size() int {
	return xxx_messageInfo_RecipeProcessConfig.Size(m)
}
func (m *RecipeProcessConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RecipeProcessConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RecipeProcessConfig proto.InternalMessageInfo

func (m *RecipeProcessConfig) GetStations() []string {
	if m != nil {
		return m.Stations
	}
	return nil
}

func (m *RecipeProcessConfig) GetBatchSize() *types.Decimal {
	if m != nil {
		return m.BatchSize
	}
	return nil
}

func (m *RecipeProcessConfig) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *RecipeProcessConfig) GetTools() []*RecipeTool {
	if m != nil {
		return m.Tools
	}
	return nil
}

func (m *RecipeProcessConfig) GetSteps() []*RecipeProcessStep {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *RecipeProcessConfig) GetCommonsControls() []*RecipeProperty {
	if m != nil {
		return m.CommonsControls
	}
	return nil
}

func (m *RecipeProcessConfig) GetCommonsProperties() []*RecipeProperty {
	if m != nil {
		return m.CommonsProperties
	}
	return nil
}

type OutputProduct struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutputProduct) Reset()         { *m = OutputProduct{} }
func (m *OutputProduct) String() string { return proto.CompactTextString(m) }
func (*OutputProduct) ProtoMessage()    {}
func (*OutputProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad217bbbd342a47f, []int{7}
}

func (m *OutputProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutputProduct.Unmarshal(m, b)
}
func (m *OutputProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutputProduct.Marshal(b, m, deterministic)
}
func (m *OutputProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutputProduct.Merge(m, src)
}
func (m *OutputProduct) XXX_Size() int {
	return xxx_messageInfo_OutputProduct.Size(m)
}
func (m *OutputProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_OutputProduct.DiscardUnknown(m)
}

var xxx_messageInfo_OutputProduct proto.InternalMessageInfo

func (m *OutputProduct) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OutputProduct) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type OptionalFlow struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// OIDs are relative to ProcessDefinition.oid.
	ProcessOids          []string `protobuf:"bytes,2,rep,name=process_oids,json=processOids,proto3" json:"process_oids,omitempty"`
	MaxRepetitions       int32    `protobuf:"varint,3,opt,name=max_repetitions,json=maxRepetitions,proto3" json:"max_repetitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OptionalFlow) Reset()         { *m = OptionalFlow{} }
func (m *OptionalFlow) String() string { return proto.CompactTextString(m) }
func (*OptionalFlow) ProtoMessage()    {}
func (*OptionalFlow) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad217bbbd342a47f, []int{8}
}

func (m *OptionalFlow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OptionalFlow.Unmarshal(m, b)
}
func (m *OptionalFlow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OptionalFlow.Marshal(b, m, deterministic)
}
func (m *OptionalFlow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptionalFlow.Merge(m, src)
}
func (m *OptionalFlow) XXX_Size() int {
	return xxx_messageInfo_OptionalFlow.Size(m)
}
func (m *OptionalFlow) XXX_DiscardUnknown() {
	xxx_messageInfo_OptionalFlow.DiscardUnknown(m)
}

var xxx_messageInfo_OptionalFlow proto.InternalMessageInfo

func (m *OptionalFlow) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OptionalFlow) GetProcessOids() []string {
	if m != nil {
		return m.ProcessOids
	}
	return nil
}

func (m *OptionalFlow) GetMaxRepetitions() int32 {
	if m != nil {
		return m.MaxRepetitions
	}
	return 0
}

type Process struct {
	// The OID is relative to ProcessDefinition.oid.
	ReferenceOid         string          `protobuf:"bytes,1,opt,name=reference_oid,json=referenceOid,proto3" json:"reference_oid,omitempty"`
	OptionalFlows        []*OptionalFlow `protobuf:"bytes,2,rep,name=optional_flows,json=optionalFlows,proto3" json:"optional_flows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Process) Reset()         { *m = Process{} }
func (m *Process) String() string { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()    {}
func (*Process) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad217bbbd342a47f, []int{9}
}

func (m *Process) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process.Unmarshal(m, b)
}
func (m *Process) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process.Marshal(b, m, deterministic)
}
func (m *Process) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process.Merge(m, src)
}
func (m *Process) XXX_Size() int {
	return xxx_messageInfo_Process.Size(m)
}
func (m *Process) XXX_DiscardUnknown() {
	xxx_messageInfo_Process.DiscardUnknown(m)
}

var xxx_messageInfo_Process proto.InternalMessageInfo

func (m *Process) GetReferenceOid() string {
	if m != nil {
		return m.ReferenceOid
	}
	return ""
}

func (m *Process) GetOptionalFlows() []*OptionalFlow {
	if m != nil {
		return m.OptionalFlows
	}
	return nil
}

type RecipeVersion struct {
	Major                string               `protobuf:"bytes,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor                string               `protobuf:"bytes,2,opt,name=minor,proto3" json:"minor,omitempty"`
	Stage                string               `protobuf:"bytes,3,opt,name=stage,proto3" json:"stage,omitempty"`
	ReleasedAt           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=released_at,json=releasedAt,proto3" json:"released_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RecipeVersion) Reset()         { *m = RecipeVersion{} }
func (m *RecipeVersion) String() string { return proto.CompactTextString(m) }
func (*RecipeVersion) ProtoMessage()    {}
func (*RecipeVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad217bbbd342a47f, []int{10}
}

func (m *RecipeVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecipeVersion.Unmarshal(m, b)
}
func (m *RecipeVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecipeVersion.Marshal(b, m, deterministic)
}
func (m *RecipeVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecipeVersion.Merge(m, src)
}
func (m *RecipeVersion) XXX_Size() int {
	return xxx_messageInfo_RecipeVersion.Size(m)
}
func (m *RecipeVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_RecipeVersion.DiscardUnknown(m)
}

var xxx_messageInfo_RecipeVersion proto.InternalMessageInfo

func (m *RecipeVersion) GetMajor() string {
	if m != nil {
		return m.Major
	}
	return ""
}

func (m *RecipeVersion) GetMinor() string {
	if m != nil {
		return m.Minor
	}
	return ""
}

func (m *RecipeVersion) GetStage() string {
	if m != nil {
		return m.Stage
	}
	return ""
}

func (m *RecipeVersion) GetReleasedAt() *timestamp.Timestamp {
	if m != nil {
		return m.ReleasedAt
	}
	return nil
}

type Recipe struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductType          string               `protobuf:"bytes,2,opt,name=product_type,json=productType,proto3" json:"product_type,omitempty"`
	ProductId            string               `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Version              *RecipeVersion       `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Processes            []*Process           `protobuf:"bytes,5,rep,name=processes,proto3" json:"processes,omitempty"`
	ProcessDefs          []*ProcessDefinition `protobuf:"bytes,6,rep,name=process_defs,json=processDefs,proto3" json:"process_defs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Recipe) Reset()         { *m = Recipe{} }
func (m *Recipe) String() string { return proto.CompactTextString(m) }
func (*Recipe) ProtoMessage()    {}
func (*Recipe) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad217bbbd342a47f, []int{11}
}

func (m *Recipe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recipe.Unmarshal(m, b)
}
func (m *Recipe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recipe.Marshal(b, m, deterministic)
}
func (m *Recipe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recipe.Merge(m, src)
}
func (m *Recipe) XXX_Size() int {
	return xxx_messageInfo_Recipe.Size(m)
}
func (m *Recipe) XXX_DiscardUnknown() {
	xxx_messageInfo_Recipe.DiscardUnknown(m)
}

var xxx_messageInfo_Recipe proto.InternalMessageInfo

func (m *Recipe) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Recipe) GetProductType() string {
	if m != nil {
		return m.ProductType
	}
	return ""
}

func (m *Recipe) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *Recipe) GetVersion() *RecipeVersion {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *Recipe) GetProcesses() []*Process {
	if m != nil {
		return m.Processes
	}
	return nil
}

func (m *Recipe) GetProcessDefs() []*ProcessDefinition {
	if m != nil {
		return m.ProcessDefs
	}
	return nil
}

type ProcessDefinition struct {
	Oid                  string                    `protobuf:"bytes,1,opt,name=oid,proto3" json:"oid,omitempty"`
	Name                 string                    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string                    `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Configs              []*RecipeProcessConfig    `protobuf:"bytes,4,rep,name=configs,proto3" json:"configs,omitempty"`
	Product              *OutputProduct            `protobuf:"bytes,5,opt,name=product,proto3" json:"product,omitempty"`
	ProductValidPeriod   *ProductValidPeriodConfig `protobuf:"bytes,6,opt,name=ProductValidPeriod,proto3" json:"ProductValidPeriod,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ProcessDefinition) Reset()         { *m = ProcessDefinition{} }
func (m *ProcessDefinition) String() string { return proto.CompactTextString(m) }
func (*ProcessDefinition) ProtoMessage()    {}
func (*ProcessDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad217bbbd342a47f, []int{12}
}

func (m *ProcessDefinition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessDefinition.Unmarshal(m, b)
}
func (m *ProcessDefinition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessDefinition.Marshal(b, m, deterministic)
}
func (m *ProcessDefinition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessDefinition.Merge(m, src)
}
func (m *ProcessDefinition) XXX_Size() int {
	return xxx_messageInfo_ProcessDefinition.Size(m)
}
func (m *ProcessDefinition) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessDefinition.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessDefinition proto.InternalMessageInfo

func (m *ProcessDefinition) GetOid() string {
	if m != nil {
		return m.Oid
	}
	return ""
}

func (m *ProcessDefinition) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProcessDefinition) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ProcessDefinition) GetConfigs() []*RecipeProcessConfig {
	if m != nil {
		return m.Configs
	}
	return nil
}

func (m *ProcessDefinition) GetProduct() *OutputProduct {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *ProcessDefinition) GetProductValidPeriod() *ProductValidPeriodConfig {
	if m != nil {
		return m.ProductValidPeriod
	}
	return nil
}

type CreateRecipesRequest struct {
	Recipes              []*Recipe `protobuf:"bytes,1,rep,name=recipes,proto3" json:"recipes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateRecipesRequest) Reset()         { *m = CreateRecipesRequest{} }
func (m *CreateRecipesRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRecipesRequest) ProtoMessage()    {}
func (*CreateRecipesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad217bbbd342a47f, []int{13}
}

func (m *CreateRecipesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRecipesRequest.Unmarshal(m, b)
}
func (m *CreateRecipesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRecipesRequest.Marshal(b, m, deterministic)
}
func (m *CreateRecipesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRecipesRequest.Merge(m, src)
}
func (m *CreateRecipesRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRecipesRequest.Size(m)
}
func (m *CreateRecipesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRecipesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRecipesRequest proto.InternalMessageInfo

func (m *CreateRecipesRequest) GetRecipes() []*Recipe {
	if m != nil {
		return m.Recipes
	}
	return nil
}

type DeleteRecipesRequest struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRecipesRequest) Reset()         { *m = DeleteRecipesRequest{} }
func (m *DeleteRecipesRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRecipesRequest) ProtoMessage()    {}
func (*DeleteRecipesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad217bbbd342a47f, []int{14}
}

func (m *DeleteRecipesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRecipesRequest.Unmarshal(m, b)
}
func (m *DeleteRecipesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRecipesRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRecipesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRecipesRequest.Merge(m, src)
}
func (m *DeleteRecipesRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRecipesRequest.Size(m)
}
func (m *DeleteRecipesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRecipesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRecipesRequest proto.InternalMessageInfo

func (m *DeleteRecipesRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type Material struct {
	// id 材料代號
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Grade                string   `protobuf:"bytes,2,opt,name=grade,proto3" json:"grade,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Material) Reset()         { *m = Material{} }
func (m *Material) String() string { return proto.CompactTextString(m) }
func (*Material) ProtoMessage()    {}
func (*Material) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad217bbbd342a47f, []int{15}
}

func (m *Material) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Material.Unmarshal(m, b)
}
func (m *Material) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Material.Marshal(b, m, deterministic)
}
func (m *Material) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Material.Merge(m, src)
}
func (m *Material) XXX_Size() int {
	return xxx_messageInfo_Material.Size(m)
}
func (m *Material) XXX_DiscardUnknown() {
	xxx_messageInfo_Material.DiscardUnknown(m)
}

var xxx_messageInfo_Material proto.InternalMessageInfo

func (m *Material) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Material) GetGrade() string {
	if m != nil {
		return m.Grade
	}
	return ""
}

type Substitutions struct {
	Material             *Material      `protobuf:"bytes,1,opt,name=material,proto3" json:"material,omitempty"`
	Proportion           *types.Decimal `protobuf:"bytes,2,opt,name=proportion,proto3" json:"proportion,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Substitutions) Reset()         { *m = Substitutions{} }
func (m *Substitutions) String() string { return proto.CompactTextString(m) }
func (*Substitutions) ProtoMessage()    {}
func (*Substitutions) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad217bbbd342a47f, []int{16}
}

func (m *Substitutions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Substitutions.Unmarshal(m, b)
}
func (m *Substitutions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Substitutions.Marshal(b, m, deterministic)
}
func (m *Substitutions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Substitutions.Merge(m, src)
}
func (m *Substitutions) XXX_Size() int {
	return xxx_messageInfo_Substitutions.Size(m)
}
func (m *Substitutions) XXX_DiscardUnknown() {
	xxx_messageInfo_Substitutions.DiscardUnknown(m)
}

var xxx_messageInfo_Substitutions proto.InternalMessageInfo

func (m *Substitutions) GetMaterial() *Material {
	if m != nil {
		return m.Material
	}
	return nil
}

func (m *Substitutions) GetProportion() *types.Decimal {
	if m != nil {
		return m.Proportion
	}
	return nil
}

type CreateSubstitutionRequest struct {
	Material             *Material        `protobuf:"bytes,1,opt,name=material,proto3" json:"material,omitempty"`
	Substitutions        []*Substitutions `protobuf:"bytes,2,rep,name=substitutions,proto3" json:"substitutions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateSubstitutionRequest) Reset()         { *m = CreateSubstitutionRequest{} }
func (m *CreateSubstitutionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSubstitutionRequest) ProtoMessage()    {}
func (*CreateSubstitutionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad217bbbd342a47f, []int{17}
}

func (m *CreateSubstitutionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSubstitutionRequest.Unmarshal(m, b)
}
func (m *CreateSubstitutionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSubstitutionRequest.Marshal(b, m, deterministic)
}
func (m *CreateSubstitutionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSubstitutionRequest.Merge(m, src)
}
func (m *CreateSubstitutionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSubstitutionRequest.Size(m)
}
func (m *CreateSubstitutionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSubstitutionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSubstitutionRequest proto.InternalMessageInfo

func (m *CreateSubstitutionRequest) GetMaterial() *Material {
	if m != nil {
		return m.Material
	}
	return nil
}

func (m *CreateSubstitutionRequest) GetSubstitutions() []*Substitutions {
	if m != nil {
		return m.Substitutions
	}
	return nil
}

type UpdateSubstitutionRequest struct {
	Material             *Material        `protobuf:"bytes,1,opt,name=material,proto3" json:"material,omitempty"`
	Substitutions        []*Substitutions `protobuf:"bytes,2,rep,name=substitutions,proto3" json:"substitutions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateSubstitutionRequest) Reset()         { *m = UpdateSubstitutionRequest{} }
func (m *UpdateSubstitutionRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSubstitutionRequest) ProtoMessage()    {}
func (*UpdateSubstitutionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad217bbbd342a47f, []int{18}
}

func (m *UpdateSubstitutionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSubstitutionRequest.Unmarshal(m, b)
}
func (m *UpdateSubstitutionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSubstitutionRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSubstitutionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSubstitutionRequest.Merge(m, src)
}
func (m *UpdateSubstitutionRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSubstitutionRequest.Size(m)
}
func (m *UpdateSubstitutionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSubstitutionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSubstitutionRequest proto.InternalMessageInfo

func (m *UpdateSubstitutionRequest) GetMaterial() *Material {
	if m != nil {
		return m.Material
	}
	return nil
}

func (m *UpdateSubstitutionRequest) GetSubstitutions() []*Substitutions {
	if m != nil {
		return m.Substitutions
	}
	return nil
}

type DeleteSubstitutionRequest struct {
	Material *Material `protobuf:"bytes,1,opt,name=material,proto3" json:"material,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*DeleteSubstitutionRequest_All
	//	*DeleteSubstitutionRequest_Multiple
	Type                 isDeleteSubstitutionRequest_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *DeleteSubstitutionRequest) Reset()         { *m = DeleteSubstitutionRequest{} }
func (m *DeleteSubstitutionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSubstitutionRequest) ProtoMessage()    {}
func (*DeleteSubstitutionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad217bbbd342a47f, []int{19}
}

func (m *DeleteSubstitutionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSubstitutionRequest.Unmarshal(m, b)
}
func (m *DeleteSubstitutionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSubstitutionRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSubstitutionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSubstitutionRequest.Merge(m, src)
}
func (m *DeleteSubstitutionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSubstitutionRequest.Size(m)
}
func (m *DeleteSubstitutionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSubstitutionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSubstitutionRequest proto.InternalMessageInfo

func (m *DeleteSubstitutionRequest) GetMaterial() *Material {
	if m != nil {
		return m.Material
	}
	return nil
}

type isDeleteSubstitutionRequest_Type interface {
	isDeleteSubstitutionRequest_Type()
}

type DeleteSubstitutionRequest_All struct {
	All bool `protobuf:"varint,2,opt,name=all,proto3,oneof"`
}

type DeleteSubstitutionRequest_Multiple struct {
	Multiple *DeleteSubstitutionRequest_Batch `protobuf:"bytes,3,opt,name=multiple,proto3,oneof"`
}

func (*DeleteSubstitutionRequest_All) isDeleteSubstitutionRequest_Type() {}

func (*DeleteSubstitutionRequest_Multiple) isDeleteSubstitutionRequest_Type() {}

func (m *DeleteSubstitutionRequest) GetType() isDeleteSubstitutionRequest_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *DeleteSubstitutionRequest) GetAll() bool {
	if x, ok := m.GetType().(*DeleteSubstitutionRequest_All); ok {
		return x.All
	}
	return false
}

func (m *DeleteSubstitutionRequest) GetMultiple() *DeleteSubstitutionRequest_Batch {
	if x, ok := m.GetType().(*DeleteSubstitutionRequest_Multiple); ok {
		return x.Multiple
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DeleteSubstitutionRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DeleteSubstitutionRequest_All)(nil),
		(*DeleteSubstitutionRequest_Multiple)(nil),
	}
}

type DeleteSubstitutionRequest_Batch struct {
	Substitutions        []*Material `protobuf:"bytes,1,rep,name=substitutions,proto3" json:"substitutions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DeleteSubstitutionRequest_Batch) Reset()         { *m = DeleteSubstitutionRequest_Batch{} }
func (m *DeleteSubstitutionRequest_Batch) String() string { return proto.CompactTextString(m) }
func (*DeleteSubstitutionRequest_Batch) ProtoMessage()    {}
func (*DeleteSubstitutionRequest_Batch) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad217bbbd342a47f, []int{19, 0}
}

func (m *DeleteSubstitutionRequest_Batch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSubstitutionRequest_Batch.Unmarshal(m, b)
}
func (m *DeleteSubstitutionRequest_Batch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSubstitutionRequest_Batch.Marshal(b, m, deterministic)
}
func (m *DeleteSubstitutionRequest_Batch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSubstitutionRequest_Batch.Merge(m, src)
}
func (m *DeleteSubstitutionRequest_Batch) XXX_Size() int {
	return xxx_messageInfo_DeleteSubstitutionRequest_Batch.Size(m)
}
func (m *DeleteSubstitutionRequest_Batch) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSubstitutionRequest_Batch.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSubstitutionRequest_Batch proto.InternalMessageInfo

func (m *DeleteSubstitutionRequest_Batch) GetSubstitutions() []*Material {
	if m != nil {
		return m.Substitutions
	}
	return nil
}

type ProductValidPeriodConfig struct {
	Standing             int32    `protobuf:"varint,1,opt,name=standing,proto3" json:"standing,omitempty"`
	Expiry               int32    `protobuf:"varint,2,opt,name=expiry,proto3" json:"expiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductValidPeriodConfig) Reset()         { *m = ProductValidPeriodConfig{} }
func (m *ProductValidPeriodConfig) String() string { return proto.CompactTextString(m) }
func (*ProductValidPeriodConfig) ProtoMessage()    {}
func (*ProductValidPeriodConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad217bbbd342a47f, []int{20}
}

func (m *ProductValidPeriodConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductValidPeriodConfig.Unmarshal(m, b)
}
func (m *ProductValidPeriodConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductValidPeriodConfig.Marshal(b, m, deterministic)
}
func (m *ProductValidPeriodConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductValidPeriodConfig.Merge(m, src)
}
func (m *ProductValidPeriodConfig) XXX_Size() int {
	return xxx_messageInfo_ProductValidPeriodConfig.Size(m)
}
func (m *ProductValidPeriodConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductValidPeriodConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProductValidPeriodConfig proto.InternalMessageInfo

func (m *ProductValidPeriodConfig) GetStanding() int32 {
	if m != nil {
		return m.Standing
	}
	return 0
}

func (m *ProductValidPeriodConfig) GetExpiry() int32 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

func init() {
	proto.RegisterType((*RecipePropertyParameter)(nil), "kenda.mesync.RecipePropertyParameter")
	proto.RegisterType((*RecipeProperty)(nil), "kenda.mesync.RecipeProperty")
	proto.RegisterType((*RecipeMaterialParameter)(nil), "kenda.mesync.RecipeMaterialParameter")
	proto.RegisterType((*RecipeMaterial)(nil), "kenda.mesync.RecipeMaterial")
	proto.RegisterType((*RecipeProcessStep)(nil), "kenda.mesync.RecipeProcessStep")
	proto.RegisterType((*RecipeTool)(nil), "kenda.mesync.RecipeTool")
	proto.RegisterType((*RecipeProcessConfig)(nil), "kenda.mesync.RecipeProcessConfig")
	proto.RegisterType((*OutputProduct)(nil), "kenda.mesync.OutputProduct")
	proto.RegisterType((*OptionalFlow)(nil), "kenda.mesync.OptionalFlow")
	proto.RegisterType((*Process)(nil), "kenda.mesync.Process")
	proto.RegisterType((*RecipeVersion)(nil), "kenda.mesync.RecipeVersion")
	proto.RegisterType((*Recipe)(nil), "kenda.mesync.Recipe")
	proto.RegisterType((*ProcessDefinition)(nil), "kenda.mesync.ProcessDefinition")
	proto.RegisterType((*CreateRecipesRequest)(nil), "kenda.mesync.CreateRecipesRequest")
	proto.RegisterType((*DeleteRecipesRequest)(nil), "kenda.mesync.DeleteRecipesRequest")
	proto.RegisterType((*Material)(nil), "kenda.mesync.Material")
	proto.RegisterType((*Substitutions)(nil), "kenda.mesync.Substitutions")
	proto.RegisterType((*CreateSubstitutionRequest)(nil), "kenda.mesync.CreateSubstitutionRequest")
	proto.RegisterType((*UpdateSubstitutionRequest)(nil), "kenda.mesync.UpdateSubstitutionRequest")
	proto.RegisterType((*DeleteSubstitutionRequest)(nil), "kenda.mesync.DeleteSubstitutionRequest")
	proto.RegisterType((*DeleteSubstitutionRequest_Batch)(nil), "kenda.mesync.DeleteSubstitutionRequest.Batch")
	proto.RegisterType((*ProductValidPeriodConfig)(nil), "kenda.mesync.ProductValidPeriodConfig")
}

func init() { proto.RegisterFile("kenda/mesync/recipe.proto", fileDescriptor_ad217bbbd342a47f) }

var fileDescriptor_ad217bbbd342a47f = []byte{
	// 1184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xcd, 0x6e, 0x1c, 0x45,
	0x10, 0xce, 0xec, 0x7a, 0xed, 0xdd, 0xf2, 0x4f, 0x9c, 0xc6, 0x24, 0x13, 0x03, 0x4a, 0x32, 0x88,
	0xe0, 0x03, 0xac, 0x91, 0x4d, 0x24, 0x94, 0xe4, 0x40, 0x1c, 0x13, 0x12, 0x05, 0xb0, 0xd5, 0x09,
	0x39, 0x70, 0x59, 0xb5, 0x77, 0x6a, 0x37, 0x4d, 0x66, 0xa6, 0x27, 0xdd, 0x3d, 0x71, 0x9c, 0x47,
	0xe0, 0xc0, 0x81, 0x1b, 0x4f, 0xc0, 0xc3, 0x20, 0x9e, 0x87, 0x23, 0xa8, 0x7f, 0x66, 0x76, 0xc6,
	0xfb, 0xa3, 0x08, 0x71, 0xc8, 0xc5, 0xea, 0xea, 0xf9, 0xaa, 0xba, 0xea, 0xab, 0xbf, 0x35, 0x5c,
	0x7d, 0x81, 0x59, 0xcc, 0x76, 0x53, 0x54, 0x67, 0xd9, 0x70, 0x57, 0xe2, 0x90, 0xe7, 0xd8, 0xcf,
	0xa5, 0xd0, 0x82, 0xac, 0xd9, 0x4f, 0x7d, 0xf7, 0x69, 0xfb, 0x8a, 0x03, 0xea, 0xb3, 0x1c, 0x95,
	0xfb, 0xeb, 0x60, 0xdb, 0xd7, 0xc6, 0x42, 0x8c, 0x13, 0xdc, 0xb5, 0xd2, 0x49, 0x31, 0xda, 0xd5,
	0x3c, 0x45, 0xa5, 0x59, 0x9a, 0x3b, 0x40, 0xf4, 0x47, 0x00, 0x57, 0xa8, 0x35, 0x7c, 0x2c, 0x45,
	0x8e, 0x52, 0x9f, 0x1d, 0x33, 0xc9, 0x52, 0xd4, 0x28, 0xc9, 0x0e, 0x2c, 0x3d, 0xe7, 0xe3, 0xe7,
	0x61, 0x70, 0x3d, 0xd8, 0x59, 0xdd, 0xdb, 0xea, 0xbb, 0x27, 0x9d, 0xf9, 0x43, 0x1c, 0xf2, 0x94,
	0x25, 0xd4, 0x22, 0xc8, 0x4d, 0x68, 0xa7, 0x3c, 0x0e, 0x5b, 0x0b, 0x80, 0x06, 0x60, 0x70, 0x89,
	0x38, 0x0d, 0xdb, 0x8b, 0x70, 0x89, 0x38, 0x25, 0x04, 0x96, 0x8a, 0x8c, 0xeb, 0x70, 0xe9, 0x7a,
	0xb0, 0xd3, 0xa3, 0xf6, 0x1c, 0x31, 0xd8, 0x68, 0x3a, 0x6a, 0x50, 0x19, 0x4b, 0xd1, 0xfa, 0xd7,
	0xa3, 0xf6, 0x4c, 0xee, 0x40, 0x27, 0x37, 0x01, 0x78, 0x5f, 0x3e, 0xe9, 0xd7, 0x79, 0xea, 0xcf,
	0x89, 0x94, 0x3a, 0x9d, 0x1a, 0x19, 0xdf, 0x33, 0x8d, 0x92, 0xb3, 0xe4, 0x5d, 0x25, 0xe3, 0xaf,
	0xa0, 0x64, 0xa3, 0xf4, 0x74, 0x26, 0x1b, 0x04, 0x96, 0x8c, 0x41, 0xeb, 0x4b, 0x8f, 0xda, 0x33,
	0xd9, 0x82, 0xce, 0x58, 0xb2, 0x18, 0xed, 0xc3, 0x3d, 0xea, 0x04, 0xc3, 0xdb, 0x2b, 0x96, 0x14,
	0x68, 0x5f, 0x99, 0xc3, 0xdb, 0x14, 0x29, 0xd4, 0xe9, 0x98, 0x67, 0x14, 0xd7, 0x18, 0x76, 0xdc,
	0x33, 0xe6, 0x4c, 0x3e, 0x03, 0x22, 0xf1, 0x65, 0xc1, 0x25, 0xc6, 0x03, 0x57, 0xb9, 0x03, 0x1e,
	0x87, 0xcb, 0x16, 0xb1, 0x59, 0x7e, 0x71, 0x76, 0x1f, 0xc5, 0xd1, 0x9f, 0x01, 0x5c, 0xaa, 0x92,
	0x33, 0x44, 0xa5, 0x9e, 0x68, 0xcc, 0xc9, 0x6d, 0xe8, 0xa5, 0xfe, 0x4d, 0x15, 0x06, 0xd7, 0xdb,
	0x3b, 0xab, 0x7b, 0x1f, 0x2e, 0x72, 0x8c, 0x4e, 0xe0, 0xe4, 0x2b, 0xe8, 0x0e, 0x45, 0xa6, 0xa5,
	0x48, 0x54, 0xd8, 0x9a, 0xaf, 0x5a, 0xd6, 0x02, 0xad, 0xd0, 0xe4, 0x6b, 0x58, 0x4b, 0x91, 0xa9,
	0x42, 0x62, 0x8a, 0x99, 0x56, 0x61, 0xfb, 0x2d, 0xb4, 0x1b, 0x1a, 0xd1, 0x77, 0x00, 0xee, 0xfb,
	0x53, 0x21, 0x92, 0x2a, 0x09, 0x41, 0x2d, 0x09, 0x1b, 0xd0, 0xf2, 0x25, 0xd2, 0xa3, 0x2d, 0x1e,
	0x93, 0x6d, 0xe8, 0x96, 0x9c, 0xd8, 0xbc, 0x74, 0x69, 0x25, 0x47, 0x7f, 0xb7, 0xe0, 0xbd, 0x06,
	0x37, 0xf7, 0x45, 0x36, 0xe2, 0x63, 0xa3, 0xa3, 0x34, 0xd3, 0x5c, 0x64, 0x8e, 0x9c, 0x1e, 0xad,
	0x64, 0xb2, 0x0f, 0x70, 0xc2, 0xf4, 0xf0, 0xf9, 0x40, 0xf1, 0x37, 0xb8, 0xb0, 0x14, 0x7b, 0x16,
	0xf7, 0x84, 0xbf, 0xc1, 0xaa, 0xd0, 0xda, 0x93, 0x42, 0x23, 0x7d, 0xe8, 0x68, 0x61, 0x38, 0x5c,
	0xb2, 0x2c, 0x84, 0xb3, 0x58, 0x30, 0x51, 0x52, 0x07, 0x23, 0xb7, 0xa0, 0xa3, 0x34, 0xe6, 0x2a,
	0xec, 0x58, 0xfc, 0xb5, 0x39, 0xac, 0x95, 0x29, 0xa6, 0x0e, 0x4d, 0xbe, 0x85, 0xcd, 0xa1, 0x48,
	0x53, 0x91, 0xa9, 0x41, 0x95, 0xb5, 0xe5, 0xb7, 0xe0, 0xfd, 0xa2, 0xd7, 0xba, 0x5f, 0x26, 0xef,
	0x31, 0x90, 0xd2, 0x50, 0xee, 0x40, 0x1c, 0x55, 0xb8, 0xf2, 0x16, 0xa6, 0x2e, 0x79, 0xbd, 0xe3,
	0x4a, 0x2d, 0xda, 0x87, 0xf5, 0xa3, 0x42, 0xe7, 0x85, 0x3e, 0x96, 0x22, 0x2e, 0x86, 0xda, 0xa7,
	0x2d, 0xa8, 0xd2, 0x36, 0xa3, 0xbf, 0xa2, 0x0c, 0xd6, 0x8e, 0x72, 0x93, 0x05, 0x96, 0x3c, 0xf0,
	0xed, 0x3b, 0xd5, 0x97, 0x37, 0x60, 0x2d, 0x77, 0x24, 0x0c, 0x04, 0x8f, 0x5d, 0x81, 0xf6, 0xe8,
	0xaa, 0xbf, 0x3b, 0xe2, 0xb1, 0x22, 0x9f, 0xc2, 0xc5, 0x94, 0xbd, 0x1e, 0x48, 0xcc, 0x51, 0x73,
	0x97, 0x64, 0x93, 0x97, 0x0e, 0xdd, 0x48, 0xd9, 0x6b, 0x3a, 0xb9, 0x8d, 0x5e, 0xc2, 0x8a, 0x27,
	0x94, 0x7c, 0x0c, 0xeb, 0x12, 0x47, 0x28, 0x31, 0x1b, 0xa2, 0x31, 0xec, 0xdf, 0x5c, 0xab, 0x2e,
	0x8f, 0x78, 0x4c, 0xee, 0xc1, 0x86, 0xf0, 0xfe, 0x0d, 0x46, 0x89, 0x38, 0x2d, 0xdb, 0x63, 0xbb,
	0xc9, 0x4e, 0x3d, 0x06, 0xba, 0x2e, 0x6a, 0x92, 0x8a, 0x7e, 0x0d, 0x60, 0xdd, 0xb1, 0xf7, 0x0c,
	0xa5, 0xe2, 0x22, 0x33, 0x43, 0x25, 0x65, 0x3f, 0x0b, 0xe9, 0x5f, 0x74, 0x82, 0xbd, 0xe5, 0x99,
	0x90, 0x9e, 0x1f, 0x27, 0x98, 0x5b, 0xa5, 0xd9, 0xb8, 0x1a, 0x40, 0x56, 0x20, 0x77, 0x60, 0x55,
	0x62, 0x82, 0x4c, 0x61, 0x3c, 0x60, 0xda, 0x8f, 0xa1, 0xed, 0xbe, 0xdb, 0x5f, 0xfd, 0x72, 0x7f,
	0xf5, 0x9f, 0x96, 0xfb, 0x8b, 0x42, 0x09, 0xbf, 0xa7, 0xa3, 0x5f, 0x5a, 0xb0, 0xec, 0x1c, 0x9a,
	0x4a, 0x91, 0xa3, 0xda, 0x64, 0x6f, 0x50, 0x4b, 0xd5, 0xaa, 0xbf, 0x7b, 0x6a, 0x9a, 0xf1, 0x23,
	0x80, 0x12, 0xc2, 0x63, 0xef, 0x55, 0xcf, 0xdf, 0x3c, 0x8a, 0xc9, 0x2d, 0x58, 0x79, 0xe5, 0xc2,
	0xf4, 0x5e, 0x7d, 0x30, 0xab, 0x8e, 0x3c, 0x13, 0xb4, 0xc4, 0x92, 0x7d, 0xe8, 0xf9, 0x7c, 0x62,
	0xd9, 0x0d, 0xef, 0x37, 0x15, 0x7d, 0xda, 0xe8, 0x04, 0x47, 0x0e, 0x26, 0x85, 0x11, 0xe3, 0xa8,
	0xec, 0x81, 0x6b, 0x33, 0xf5, 0x0e, 0x71, 0xc4, 0x33, 0x5b, 0x04, 0x55, 0xe5, 0x1c, 0xe2, 0x48,
	0x45, 0xbf, 0xb7, 0xe0, 0xd2, 0x14, 0x84, 0x6c, 0x42, 0x7b, 0x52, 0x11, 0xe6, 0x58, 0x15, 0x66,
	0x6b, 0xc6, 0xc2, 0x68, 0xd7, 0x66, 0xd5, 0x1d, 0x58, 0x19, 0xda, 0x89, 0x53, 0x0e, 0x81, 0x1b,
	0x0b, 0x9a, 0xda, 0xcd, 0x26, 0x5a, 0x6a, 0x18, 0xf2, 0x3c, 0x93, 0x76, 0x3b, 0x4c, 0x91, 0xd7,
	0xe8, 0x2f, 0x5a, 0x62, 0xc9, 0x33, 0x20, 0xfe, 0xee, 0x19, 0x4b, 0x78, 0x7c, 0x8c, 0x92, 0x0b,
	0xb7, 0x3d, 0x56, 0xf7, 0x6e, 0x4e, 0xb1, 0x71, 0x0e, 0xe7, 0x7d, 0x98, 0x61, 0x21, 0x7a, 0x00,
	0x5b, 0xf7, 0x25, 0x32, 0x8d, 0xce, 0x69, 0x45, 0xf1, 0x65, 0x81, 0xca, 0x8c, 0xb9, 0x15, 0xb7,
	0xa4, 0xca, 0x3d, 0xb3, 0x35, 0x2b, 0x46, 0x5a, 0x82, 0xa2, 0x1d, 0xd8, 0x3a, 0xc4, 0x04, 0xa7,
	0xec, 0x6c, 0x42, 0xdb, 0xf4, 0xb3, 0x1b, 0xc7, 0xe6, 0x18, 0x7d, 0x01, 0xdd, 0x6a, 0x45, 0x9f,
	0xaf, 0xcd, 0x6a, 0x15, 0xb7, 0x6a, 0xab, 0x38, 0x3a, 0x83, 0xf5, 0x27, 0xc5, 0x89, 0xd2, 0x5c,
	0x17, 0x6e, 0x98, 0xef, 0x41, 0xb7, 0xdc, 0x6b, 0xfe, 0xe7, 0xc7, 0xe5, 0xa6, 0x77, 0xd5, 0xfe,
	0xab, 0x70, 0xe4, 0x4b, 0x5b, 0xd3, 0xb9, 0x90, 0xc6, 0xc4, 0xc2, 0x05, 0x50, 0xc3, 0x45, 0xbf,
	0x05, 0x70, 0xd5, 0xf1, 0x53, 0xf7, 0xa0, 0x0c, 0xee, 0xbf, 0xf8, 0x71, 0x0f, 0xd6, 0x55, 0x3d,
	0x18, 0x3f, 0x6c, 0xce, 0x55, 0x41, 0x23, 0x5e, 0xda, 0xd4, 0xb0, 0x4e, 0xfd, 0x98, 0xc7, 0xef,
	0x96, 0x53, 0xff, 0x04, 0x70, 0xd5, 0x55, 0xc0, 0xff, 0xe5, 0x14, 0x81, 0x36, 0x4b, 0x12, 0x9b,
	0xaa, 0xee, 0xc3, 0x0b, 0xd4, 0x08, 0xe4, 0x31, 0x74, 0xd3, 0x22, 0xd1, 0x3c, 0x4f, 0xd0, 0xff,
	0x4e, 0xfc, 0xbc, 0x69, 0x67, 0xae, 0x0b, 0xfd, 0x03, 0xb3, 0xd6, 0x1f, 0x5e, 0xa0, 0x95, 0x81,
	0xed, 0x6f, 0xa0, 0x63, 0x2f, 0xc9, 0xdd, 0xf3, 0xe1, 0xbb, 0x92, 0x9f, 0xe7, 0x62, 0x13, 0x7c,
	0xb0, 0xec, 0x46, 0x44, 0xf4, 0x03, 0x84, 0xf3, 0x5a, 0xcf, 0xff, 0x34, 0xc9, 0x62, 0x9e, 0x8d,
	0x6d, 0xfc, 0x1d, 0x5a, 0xc9, 0xe4, 0x32, 0x2c, 0xe3, 0xeb, 0x9c, 0xcb, 0x33, 0x1b, 0x6a, 0x87,
	0x7a, 0xe9, 0xe0, 0xee, 0x4f, 0xb7, 0xc7, 0x5c, 0x27, 0xec, 0xc4, 0xbb, 0x31, 0x14, 0x69, 0x5f,
	0x9f, 0xee, 0x36, 0xfe, 0x05, 0xca, 0x5f, 0x8c, 0x27, 0xff, 0xca, 0xd4, 0xbf, 0x9c, 0x2c, 0xdb,
	0xeb, 0xfd, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x6a, 0x0a, 0x64, 0x33, 0x0d, 0x00, 0x00,
}
