// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kenda/mesync/record.proto

package mesync

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	types "gitlab.kenda.com.tw/kenda/mesync/pkg/protobuf/kenda/types"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListRecordsRequest struct {
	Date                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	DepartmentId         string               `protobuf:"bytes,2,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListRecordsRequest) Reset()         { *m = ListRecordsRequest{} }
func (m *ListRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*ListRecordsRequest) ProtoMessage()    {}
func (*ListRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_18ed33214eccee25, []int{0}
}

func (m *ListRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRecordsRequest.Unmarshal(m, b)
}
func (m *ListRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRecordsRequest.Marshal(b, m, deterministic)
}
func (m *ListRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRecordsRequest.Merge(m, src)
}
func (m *ListRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_ListRecordsRequest.Size(m)
}
func (m *ListRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRecordsRequest proto.InternalMessageInfo

func (m *ListRecordsRequest) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *ListRecordsRequest) GetDepartmentId() string {
	if m != nil {
		return m.DepartmentId
	}
	return ""
}

type Site struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Index                int32    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Site) Reset()         { *m = Site{} }
func (m *Site) String() string { return proto.CompactTextString(m) }
func (*Site) ProtoMessage()    {}
func (*Site) Descriptor() ([]byte, []int) {
	return fileDescriptor_18ed33214eccee25, []int{1}
}

func (m *Site) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Site.Unmarshal(m, b)
}
func (m *Site) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Site.Marshal(b, m, deterministic)
}
func (m *Site) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Site.Merge(m, src)
}
func (m *Site) XXX_Size() int {
	return xxx_messageInfo_Site.Size(m)
}
func (m *Site) XXX_DiscardUnknown() {
	xxx_messageInfo_Site.DiscardUnknown(m)
}

var xxx_messageInfo_Site proto.InternalMessageInfo

func (m *Site) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Site) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type FeedMaterials struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Grade                string         `protobuf:"bytes,2,opt,name=grade,proto3" json:"grade,omitempty"`
	ResourceId           string         `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Quantity             *types.Decimal `protobuf:"bytes,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Site                 *Site          `protobuf:"bytes,5,opt,name=site,proto3" json:"site,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FeedMaterials) Reset()         { *m = FeedMaterials{} }
func (m *FeedMaterials) String() string { return proto.CompactTextString(m) }
func (*FeedMaterials) ProtoMessage()    {}
func (*FeedMaterials) Descriptor() ([]byte, []int) {
	return fileDescriptor_18ed33214eccee25, []int{2}
}

func (m *FeedMaterials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedMaterials.Unmarshal(m, b)
}
func (m *FeedMaterials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedMaterials.Marshal(b, m, deterministic)
}
func (m *FeedMaterials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedMaterials.Merge(m, src)
}
func (m *FeedMaterials) XXX_Size() int {
	return xxx_messageInfo_FeedMaterials.Size(m)
}
func (m *FeedMaterials) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedMaterials.DiscardUnknown(m)
}

var xxx_messageInfo_FeedMaterials proto.InternalMessageInfo

func (m *FeedMaterials) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FeedMaterials) GetGrade() string {
	if m != nil {
		return m.Grade
	}
	return ""
}

func (m *FeedMaterials) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *FeedMaterials) GetQuantity() *types.Decimal {
	if m != nil {
		return m.Quantity
	}
	return nil
}

func (m *FeedMaterials) GetSite() *Site {
	if m != nil {
		return m.Site
	}
	return nil
}

type FeedRecord struct {
	WorkOrder            string           `protobuf:"bytes,1,opt,name=work_order,json=workOrder,proto3" json:"work_order,omitempty"`
	RecipeId             string           `protobuf:"bytes,2,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	Batch                int32            `protobuf:"varint,3,opt,name=batch,proto3" json:"batch,omitempty"`
	StationId            string           `protobuf:"bytes,5,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	Materials            []*FeedMaterials `protobuf:"bytes,6,rep,name=materials,proto3" json:"materials,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FeedRecord) Reset()         { *m = FeedRecord{} }
func (m *FeedRecord) String() string { return proto.CompactTextString(m) }
func (*FeedRecord) ProtoMessage()    {}
func (*FeedRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_18ed33214eccee25, []int{3}
}

func (m *FeedRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedRecord.Unmarshal(m, b)
}
func (m *FeedRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedRecord.Marshal(b, m, deterministic)
}
func (m *FeedRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedRecord.Merge(m, src)
}
func (m *FeedRecord) XXX_Size() int {
	return xxx_messageInfo_FeedRecord.Size(m)
}
func (m *FeedRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedRecord.DiscardUnknown(m)
}

var xxx_messageInfo_FeedRecord proto.InternalMessageInfo

func (m *FeedRecord) GetWorkOrder() string {
	if m != nil {
		return m.WorkOrder
	}
	return ""
}

func (m *FeedRecord) GetRecipeId() string {
	if m != nil {
		return m.RecipeId
	}
	return ""
}

func (m *FeedRecord) GetBatch() int32 {
	if m != nil {
		return m.Batch
	}
	return 0
}

func (m *FeedRecord) GetStationId() string {
	if m != nil {
		return m.StationId
	}
	return ""
}

func (m *FeedRecord) GetMaterials() []*FeedMaterials {
	if m != nil {
		return m.Materials
	}
	return nil
}

type FactoryFeedRecord struct {
	FactoryId            string        `protobuf:"bytes,1,opt,name=factory_id,json=factoryId,proto3" json:"factory_id,omitempty"`
	Records              []*FeedRecord `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FactoryFeedRecord) Reset()         { *m = FactoryFeedRecord{} }
func (m *FactoryFeedRecord) String() string { return proto.CompactTextString(m) }
func (*FactoryFeedRecord) ProtoMessage()    {}
func (*FactoryFeedRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_18ed33214eccee25, []int{4}
}

func (m *FactoryFeedRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FactoryFeedRecord.Unmarshal(m, b)
}
func (m *FactoryFeedRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FactoryFeedRecord.Marshal(b, m, deterministic)
}
func (m *FactoryFeedRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FactoryFeedRecord.Merge(m, src)
}
func (m *FactoryFeedRecord) XXX_Size() int {
	return xxx_messageInfo_FactoryFeedRecord.Size(m)
}
func (m *FactoryFeedRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_FactoryFeedRecord.DiscardUnknown(m)
}

var xxx_messageInfo_FactoryFeedRecord proto.InternalMessageInfo

func (m *FactoryFeedRecord) GetFactoryId() string {
	if m != nil {
		return m.FactoryId
	}
	return ""
}

func (m *FactoryFeedRecord) GetRecords() []*FeedRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

type ListFeedRecordsReply struct {
	Records              []*FactoryFeedRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListFeedRecordsReply) Reset()         { *m = ListFeedRecordsReply{} }
func (m *ListFeedRecordsReply) String() string { return proto.CompactTextString(m) }
func (*ListFeedRecordsReply) ProtoMessage()    {}
func (*ListFeedRecordsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_18ed33214eccee25, []int{5}
}

func (m *ListFeedRecordsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFeedRecordsReply.Unmarshal(m, b)
}
func (m *ListFeedRecordsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFeedRecordsReply.Marshal(b, m, deterministic)
}
func (m *ListFeedRecordsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFeedRecordsReply.Merge(m, src)
}
func (m *ListFeedRecordsReply) XXX_Size() int {
	return xxx_messageInfo_ListFeedRecordsReply.Size(m)
}
func (m *ListFeedRecordsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFeedRecordsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListFeedRecordsReply proto.InternalMessageInfo

func (m *ListFeedRecordsReply) GetRecords() []*FactoryFeedRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

type CollectRecord struct {
	ResourceId           string         `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	WorkOrder            string         `protobuf:"bytes,2,opt,name=work_order,json=workOrder,proto3" json:"work_order,omitempty"`
	RecipeId             string         `protobuf:"bytes,3,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	ProductId            string         `protobuf:"bytes,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity             *types.Decimal `protobuf:"bytes,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CollectRecord) Reset()         { *m = CollectRecord{} }
func (m *CollectRecord) String() string { return proto.CompactTextString(m) }
func (*CollectRecord) ProtoMessage()    {}
func (*CollectRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_18ed33214eccee25, []int{6}
}

func (m *CollectRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectRecord.Unmarshal(m, b)
}
func (m *CollectRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectRecord.Marshal(b, m, deterministic)
}
func (m *CollectRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectRecord.Merge(m, src)
}
func (m *CollectRecord) XXX_Size() int {
	return xxx_messageInfo_CollectRecord.Size(m)
}
func (m *CollectRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectRecord.DiscardUnknown(m)
}

var xxx_messageInfo_CollectRecord proto.InternalMessageInfo

func (m *CollectRecord) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *CollectRecord) GetWorkOrder() string {
	if m != nil {
		return m.WorkOrder
	}
	return ""
}

func (m *CollectRecord) GetRecipeId() string {
	if m != nil {
		return m.RecipeId
	}
	return ""
}

func (m *CollectRecord) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *CollectRecord) GetQuantity() *types.Decimal {
	if m != nil {
		return m.Quantity
	}
	return nil
}

type FactoryCollectRecord struct {
	FactoryId            string           `protobuf:"bytes,1,opt,name=factory_id,json=factoryId,proto3" json:"factory_id,omitempty"`
	Records              []*CollectRecord `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FactoryCollectRecord) Reset()         { *m = FactoryCollectRecord{} }
func (m *FactoryCollectRecord) String() string { return proto.CompactTextString(m) }
func (*FactoryCollectRecord) ProtoMessage()    {}
func (*FactoryCollectRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_18ed33214eccee25, []int{7}
}

func (m *FactoryCollectRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FactoryCollectRecord.Unmarshal(m, b)
}
func (m *FactoryCollectRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FactoryCollectRecord.Marshal(b, m, deterministic)
}
func (m *FactoryCollectRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FactoryCollectRecord.Merge(m, src)
}
func (m *FactoryCollectRecord) XXX_Size() int {
	return xxx_messageInfo_FactoryCollectRecord.Size(m)
}
func (m *FactoryCollectRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_FactoryCollectRecord.DiscardUnknown(m)
}

var xxx_messageInfo_FactoryCollectRecord proto.InternalMessageInfo

func (m *FactoryCollectRecord) GetFactoryId() string {
	if m != nil {
		return m.FactoryId
	}
	return ""
}

func (m *FactoryCollectRecord) GetRecords() []*CollectRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

type ListCollectRecordsReply struct {
	Records              []*FactoryCollectRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ListCollectRecordsReply) Reset()         { *m = ListCollectRecordsReply{} }
func (m *ListCollectRecordsReply) String() string { return proto.CompactTextString(m) }
func (*ListCollectRecordsReply) ProtoMessage()    {}
func (*ListCollectRecordsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_18ed33214eccee25, []int{8}
}

func (m *ListCollectRecordsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCollectRecordsReply.Unmarshal(m, b)
}
func (m *ListCollectRecordsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCollectRecordsReply.Marshal(b, m, deterministic)
}
func (m *ListCollectRecordsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCollectRecordsReply.Merge(m, src)
}
func (m *ListCollectRecordsReply) XXX_Size() int {
	return xxx_messageInfo_ListCollectRecordsReply.Size(m)
}
func (m *ListCollectRecordsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCollectRecordsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListCollectRecordsReply proto.InternalMessageInfo

func (m *ListCollectRecordsReply) GetRecords() []*FactoryCollectRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

func init() {
	proto.RegisterType((*ListRecordsRequest)(nil), "kenda.mesync.ListRecordsRequest")
	proto.RegisterType((*Site)(nil), "kenda.mesync.Site")
	proto.RegisterType((*FeedMaterials)(nil), "kenda.mesync.FeedMaterials")
	proto.RegisterType((*FeedRecord)(nil), "kenda.mesync.FeedRecord")
	proto.RegisterType((*FactoryFeedRecord)(nil), "kenda.mesync.FactoryFeedRecord")
	proto.RegisterType((*ListFeedRecordsReply)(nil), "kenda.mesync.ListFeedRecordsReply")
	proto.RegisterType((*CollectRecord)(nil), "kenda.mesync.CollectRecord")
	proto.RegisterType((*FactoryCollectRecord)(nil), "kenda.mesync.FactoryCollectRecord")
	proto.RegisterType((*ListCollectRecordsReply)(nil), "kenda.mesync.ListCollectRecordsReply")
}

func init() { proto.RegisterFile("kenda/mesync/record.proto", fileDescriptor_18ed33214eccee25) }

var fileDescriptor_18ed33214eccee25 = []byte{
	// 580 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x51, 0x6b, 0xdb, 0x3c,
	0x14, 0xc5, 0xa9, 0x9d, 0x2f, 0xbe, 0x6d, 0x3f, 0x3a, 0x11, 0xa8, 0xd7, 0x52, 0x5a, 0x3c, 0x18,
	0x79, 0x72, 0x4a, 0xc6, 0x1e, 0x3a, 0xfa, 0xb4, 0x8d, 0x42, 0xca, 0xc6, 0x98, 0x36, 0x18, 0xec,
	0x25, 0x28, 0xd6, 0x4d, 0x26, 0x62, 0x5b, 0xae, 0xa4, 0xd0, 0xe5, 0x5f, 0xed, 0x17, 0xec, 0x65,
	0x7f, 0x6c, 0x58, 0x72, 0xea, 0xda, 0x2d, 0xdb, 0x5e, 0x8c, 0x75, 0xee, 0xbd, 0x47, 0xf7, 0x9e,
	0x73, 0x11, 0x3c, 0x5d, 0x61, 0xc1, 0xd9, 0x38, 0x47, 0xbd, 0x29, 0xd2, 0xb1, 0xc2, 0x54, 0x2a,
	0x9e, 0x94, 0x4a, 0x1a, 0x49, 0xf6, 0x6c, 0x28, 0x71, 0xa1, 0xa3, 0xd3, 0xa5, 0x94, 0xcb, 0x0c,
	0xc7, 0x36, 0x36, 0x5f, 0x2f, 0xc6, 0x46, 0xe4, 0xa8, 0x0d, 0xcb, 0x4b, 0x97, 0x7e, 0x74, 0xe8,
	0x98, 0xcc, 0xa6, 0x44, 0xed, 0xbe, 0x2e, 0x10, 0x0b, 0x20, 0xef, 0x84, 0x36, 0xd4, 0x72, 0x6b,
	0x8a, 0x37, 0x6b, 0xd4, 0x86, 0x24, 0xe0, 0x73, 0x66, 0x30, 0xf2, 0xce, 0xbc, 0xd1, 0xee, 0xe4,
	0x28, 0x71, 0xf4, 0xc9, 0x96, 0x3e, 0xf9, 0xbc, 0xa5, 0xa7, 0x36, 0x8f, 0x3c, 0x83, 0x7d, 0x8e,
	0x25, 0x53, 0x26, 0xc7, 0xc2, 0xcc, 0x04, 0x8f, 0x7a, 0x67, 0xde, 0x28, 0xa4, 0x7b, 0x0d, 0x38,
	0xe5, 0xf1, 0x39, 0xf8, 0x9f, 0x84, 0x41, 0x42, 0xc0, 0x2f, 0x58, 0xee, 0xc8, 0x43, 0x6a, 0xff,
	0xc9, 0x10, 0x02, 0x51, 0x70, 0xfc, 0x6e, 0x0b, 0x03, 0xea, 0x0e, 0xf1, 0x0f, 0x0f, 0xf6, 0xaf,
	0x10, 0xf9, 0x7b, 0x66, 0x50, 0x09, 0x96, 0x69, 0xf2, 0x3f, 0xf4, 0x04, 0xaf, 0x2b, 0x7b, 0x82,
	0x57, 0x75, 0x4b, 0xc5, 0x38, 0xd6, 0x17, 0xba, 0x03, 0x39, 0x85, 0x5d, 0x85, 0x5a, 0xae, 0x55,
	0x8a, 0x55, 0x33, 0x3b, 0x36, 0x06, 0x5b, 0x68, 0xca, 0xc9, 0x39, 0x0c, 0x6e, 0xd6, 0xac, 0x30,
	0xc2, 0x6c, 0x22, 0xdf, 0xce, 0x38, 0x4c, 0x9c, 0xa0, 0x4e, 0x9b, 0xb7, 0x98, 0x8a, 0x9c, 0x65,
	0xf4, 0x2e, 0x8b, 0x3c, 0x07, 0x5f, 0x0b, 0x83, 0x51, 0x60, 0xb3, 0x49, 0x72, 0x5f, 0xfe, 0xa4,
	0x1a, 0x8b, 0xda, 0x78, 0xfc, 0xd3, 0x03, 0xa8, 0x5a, 0x76, 0x82, 0x92, 0x13, 0x80, 0x5b, 0xa9,
	0x56, 0x33, 0xa9, 0x38, 0xaa, 0xba, 0xef, 0xb0, 0x42, 0x3e, 0x54, 0x00, 0x39, 0x86, 0x50, 0x61,
	0x2a, 0x4a, 0x6c, 0x34, 0x1b, 0x38, 0x60, 0x6a, 0x67, 0x9b, 0x33, 0x93, 0x7e, 0xb3, 0xfd, 0x07,
	0xd4, 0x1d, 0x2a, 0x46, 0x6d, 0x98, 0x11, 0xb2, 0xa8, 0x6a, 0x02, 0xc7, 0x58, 0x23, 0x53, 0x4e,
	0x2e, 0x20, 0xcc, 0xb7, 0x6a, 0x45, 0xfd, 0xb3, 0x9d, 0xd1, 0xee, 0xe4, 0xb8, 0xdd, 0x6c, 0x4b,
	0x50, 0xda, 0x64, 0x5f, 0xfb, 0x03, 0xff, 0x20, 0x88, 0x17, 0xf0, 0xe4, 0x8a, 0xa5, 0x46, 0xaa,
	0x4d, 0x7b, 0x8c, 0x85, 0x03, 0x67, 0x77, 0xf2, 0x87, 0x35, 0x32, 0xe5, 0x64, 0x02, 0xff, 0xb9,
	0xe5, 0xd4, 0x51, 0xcf, 0x5e, 0x19, 0x3d, 0xbc, 0xd2, 0x31, 0xd1, 0x6d, 0x62, 0xfc, 0x11, 0x86,
	0xd5, 0xe2, 0x35, 0x21, 0x4d, 0xb1, 0xcc, 0x36, 0xe4, 0xa2, 0xe1, 0xf2, 0x2c, 0xd7, 0x69, 0x87,
	0xab, 0xdb, 0x5c, 0x43, 0xf9, 0xcb, 0x83, 0xfd, 0x37, 0x32, 0xcb, 0x30, 0xad, 0xf7, 0xb9, 0xbb,
	0x08, 0xde, 0x83, 0x45, 0x68, 0xfb, 0xd3, 0xfb, 0xa3, 0x3f, 0x3b, 0x1d, 0x7f, 0x4e, 0x00, 0x4a,
	0x25, 0xf9, 0x3a, 0xb5, 0x1b, 0xef, 0xbb, 0xda, 0x1a, 0xe9, 0xec, 0x58, 0xff, 0x5f, 0x76, 0xec,
	0xda, 0x1f, 0x04, 0x07, 0xfd, 0x38, 0x83, 0x61, 0x3d, 0x63, 0x7b, 0x96, 0xbf, 0x78, 0xf0, 0xb2,
	0xeb, 0x41, 0xc7, 0xf6, 0x16, 0x59, 0xa3, 0xd9, 0x17, 0x38, 0xac, 0x6c, 0x68, 0x45, 0x6b, 0x27,
	0x2e, 0xbb, 0x4e, 0xc4, 0x8f, 0x3a, 0xf1, 0x38, 0xf1, 0xeb, 0xcb, 0xaf, 0xaf, 0x96, 0xc2, 0x64,
	0x6c, 0x5e, 0x17, 0xa5, 0x32, 0x4f, 0xcc, 0xed, 0xb8, 0xf5, 0xa2, 0x95, 0xab, 0x65, 0xf3, 0x64,
	0xdd, 0x8f, 0xcc, 0xfb, 0x16, 0x7e, 0xf1, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xb6, 0x1b, 0xc3,
	0x02, 0x05, 0x00, 0x00,
}
