// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kenda/mesync/user.proto

package mesync

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserInfo struct {
	// id 通常為工號
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	DepartmentId         string   `protobuf:"bytes,3,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd5f32975a2d554b, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserInfo) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UserInfo) GetDepartmentId() string {
	if m != nil {
		return m.DepartmentId
	}
	return ""
}

type CreateUsersRequest struct {
	Users                []*UserInfo `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateUsersRequest) Reset()         { *m = CreateUsersRequest{} }
func (m *CreateUsersRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUsersRequest) ProtoMessage()    {}
func (*CreateUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd5f32975a2d554b, []int{1}
}

func (m *CreateUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUsersRequest.Unmarshal(m, b)
}
func (m *CreateUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUsersRequest.Marshal(b, m, deterministic)
}
func (m *CreateUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUsersRequest.Merge(m, src)
}
func (m *CreateUsersRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUsersRequest.Size(m)
}
func (m *CreateUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUsersRequest proto.InternalMessageInfo

func (m *CreateUsersRequest) GetUsers() []*UserInfo {
	if m != nil {
		return m.Users
	}
	return nil
}

type UpdateUserRequest struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Account              string               `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	DepartmentId         string               `protobuf:"bytes,3,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	LeaveDate            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=leave_date,json=leaveDate,proto3" json:"leave_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd5f32975a2d554b, []int{2}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateUserRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UpdateUserRequest) GetDepartmentId() string {
	if m != nil {
		return m.DepartmentId
	}
	return ""
}

func (m *UpdateUserRequest) GetLeaveDate() *timestamp.Timestamp {
	if m != nil {
		return m.LeaveDate
	}
	return nil
}

type DeleteUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd5f32975a2d554b, []int{3}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "kenda.mesync.UserInfo")
	proto.RegisterType((*CreateUsersRequest)(nil), "kenda.mesync.CreateUsersRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "kenda.mesync.UpdateUserRequest")
	proto.RegisterType((*DeleteUserRequest)(nil), "kenda.mesync.DeleteUserRequest")
}

func init() { proto.RegisterFile("kenda/mesync/user.proto", fileDescriptor_bd5f32975a2d554b) }

var fileDescriptor_bd5f32975a2d554b = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x95, 0x94, 0x7f, 0xbd, 0x16, 0xa4, 0x7a, 0x00, 0xab, 0x0b, 0x51, 0xba, 0x64, 0x40,
	0x8e, 0x54, 0x26, 0x10, 0x53, 0xe9, 0xd2, 0x35, 0xa2, 0x03, 0x2c, 0x95, 0x13, 0x5f, 0xa3, 0xa8,
	0x49, 0x1c, 0xe2, 0x0b, 0x88, 0x0f, 0xc3, 0x77, 0x45, 0x71, 0x1a, 0xb5, 0x2c, 0x4c, 0x8c, 0x7e,
	0xef, 0xe9, 0xee, 0xe7, 0x77, 0x70, 0xb3, 0xc3, 0x52, 0xc9, 0xb0, 0x40, 0xf3, 0x55, 0x26, 0x61,
	0x63, 0xb0, 0x16, 0x55, 0xad, 0x49, 0xb3, 0xb1, 0x35, 0x44, 0x67, 0x4c, 0x6f, 0x53, 0xad, 0xd3,
	0x1c, 0x43, 0xeb, 0xc5, 0xcd, 0x36, 0xa4, 0xac, 0x40, 0x43, 0xb2, 0xa8, 0xba, 0xb8, 0xff, 0x0a,
	0x17, 0x6b, 0x83, 0xf5, 0xaa, 0xdc, 0x6a, 0x76, 0x05, 0x6e, 0xa6, 0xb8, 0xe3, 0x39, 0xc1, 0x30,
	0x72, 0x33, 0xc5, 0x38, 0x9c, 0xcb, 0x24, 0xd1, 0x4d, 0x49, 0xdc, 0xb5, 0x62, 0xff, 0x64, 0x33,
	0xb8, 0x54, 0x58, 0xc9, 0x9a, 0x0a, 0x2c, 0x69, 0x93, 0x29, 0x3e, 0xb0, 0xfe, 0xf8, 0x20, 0xae,
	0x94, 0xbf, 0x00, 0xf6, 0x5c, 0xa3, 0x24, 0x6c, 0x17, 0x98, 0x08, 0xdf, 0x1b, 0x34, 0xc4, 0xee,
	0xe0, 0xb4, 0xa5, 0x35, 0xdc, 0xf1, 0x06, 0xc1, 0x68, 0x7e, 0x2d, 0x8e, 0x79, 0x45, 0xcf, 0x12,
	0x75, 0x21, 0xff, 0xdb, 0x81, 0xc9, 0xba, 0x52, 0xfb, 0x21, 0xfd, 0x8c, 0xff, 0x05, 0x65, 0x0f,
	0x00, 0x39, 0xca, 0x0f, 0xdc, 0xb4, 0x7b, 0xf8, 0x89, 0xe7, 0x04, 0xa3, 0xf9, 0x54, 0x74, 0xcd,
	0x89, 0xbe, 0x39, 0xf1, 0xd2, 0x37, 0x17, 0x0d, 0x6d, 0x7a, 0x29, 0x09, 0xfd, 0x19, 0x4c, 0x96,
	0x98, 0xe3, 0x9f, 0x78, 0x8b, 0xa7, 0xb7, 0xc7, 0x34, 0xa3, 0x5c, 0xc6, 0xfb, 0xbf, 0x26, 0xba,
	0x10, 0xf4, 0x19, 0xfe, 0xba, 0x60, 0xb5, 0x4b, 0x0f, 0x47, 0x3a, 0x76, 0xe2, 0x33, 0x2b, 0xdf,
	0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe4, 0xfe, 0x8b, 0xe1, 0xf2, 0x01, 0x00, 0x00,
}
